# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35db6914591e4ce5a9193e450b24f3e6980402cd56817a4fa43cd368ba468f28325647a933ec05c9bde38155b94649c6113630fc92be78da1106ea3a3854c777

test:
  secret_key_base: a81224af60c48abb93cd22f8afeb081f99d25c9552b5e0d1a3505cc411d83f3c7a180e86a2f8a48efd43a9e2ac79fadd17c810df104933c90576c89075f1be5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
